package com.pz64.rfa.data.dsp

import android.content.Context
import android.util.Log
import com.pz64.rfa.data.dsp.converter.IQConverter
import com.pz64.rfa.data.dsp.converter.Unsigned8BitIQConverter
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.net.InetSocketAddress
import java.net.Socket
import java.util.concurrent.ArrayBlockingQueue
import java.util.concurrent.TimeUnit
import kotlin.time.Duration.Companion.milliseconds

/**
 * <h1>RF Analyzer - rtl-sdr source</h1>
 *
 * Module:      RtlsdrSource.kt
 * Description: Simple source of IQ sampling by reading from IQ files generated by the
 *              HackRF. Just for testing.
 *
 * @author Dennis Mantz
 *
 * Copyright (C) 2025 Dennis Mantz
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher
 */
class RtlsdrSource(private val ipAddress: String, private val port: Int) {


    private var callback: Callback? = null
    private var socket: Socket? = null
    private var inputStream: InputStream? = null
    private var outputStream: OutputStream? = null
    private var name = "RTL-SDR"
    private var magic: String? = null
    private var tuner = RTLSDR_TUNER_UNKNOWN

    private val queue = ArrayBlockingQueue<ByteArray>(QUEUE_SIZE)
    private val returnQueue = ArrayBlockingQueue<ByteArray>(QUEUE_SIZE)

    @Volatile
    private var frequency: Long = 0

    @Volatile
    private var sampleRate: Int = 0

    @Volatile
    private var gain = 0

    @Volatile
    private var ifGain = 0

    @Volatile
    private var manualGain = true

    @Volatile
    private var frequencyCorrection = 0

    @Volatile
    private var automaticGainControl = false

    @Volatile
    private var frequencyOffset = 0

    @Volatile
    private var directSamplingMode = 0

    private val iqConverter: IQConverter = Unsigned8BitIQConverter()
    var isAllowOutOfBoundFrequency = false

    private val commandQueue = ArrayBlockingQueue<ByteArray>(20)
    private val frequencyChangeCommandQueue = ArrayBlockingQueue<ByteArray>(1)

    private var sourceScope: CoroutineScope? = null
    private var receiverJob: Job? = null
    private var commandJob: Job? = null

    init {
        for (i in 0 until QUEUE_SIZE) {
            returnQueue.offer(ByteArray(PACKET_SIZE))
        }
    }

    private fun reportError(msg: String) {
        callback?.onIQSourceError(this, msg) ?: Log.e(
            LOGTAG,
            "reportError: Callback is null. (Error: $msg)"
        )
    }

    fun open(context: Context, callback: Callback): Boolean {
        this.callback = callback
        if (sourceScope != null) {
            Log.e(LOGTAG, "open: already open or opening")
            return false
        }

        sourceScope = CoroutineScope(Dispatchers.Default + Job())
        commandJob = sourceScope?.launch {
            if (connect(5000)) {
                callback.onIQSourceReady(this@RtlsdrSource)
                commandLoop()
            } else {
                reportError("Couldn't connect to rtl_tcp instance")
                close()
            }
        }

        return true
    }

    fun isOpen(): Boolean = sourceScope != null

    fun close(): Boolean {
        sourceScope?.cancel()
        sourceScope = null

        runBlocking {
            withContext(Dispatchers.IO) {
                socket?.close()
                socket = null
                inputStream = null
                outputStream = null
            }
        }

        tuner = 0
        magic = null
        name = "RTL-SDR"
        return true
    }

    fun getName(): String = name
    fun getIpAddress(): String = ipAddress
    fun getPort(): Int = port

    fun getSampleRate(): Int = sampleRate
    fun setSampleRate(sampleRate: Int) {
        if (isOpen()) {
            if (sampleRate < getMinSampleRate() || sampleRate > getMaxSampleRate()) {
                Log.e(LOGTAG, "setSampleRate: Sample rate out of valid range: $sampleRate")
                return
            }
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_SAMPLERATE, sampleRate))
        }
        flushQueue()
        this.sampleRate = sampleRate
        iqConverter.sampleRate = sampleRate
    }

    fun getFrequency(): Long = frequency + frequencyOffset
    fun setFrequency(frequency: Long) {
        val actualSourceFrequency = frequency - frequencyOffset
        if (isOpen()) {
            if (frequency < getMinFrequency() || frequency > getMaxFrequency()) {
                Log.e(
                    LOGTAG,
                    "setFrequency: Frequency out of valid range: $frequency (upconverterFrequency=$frequencyOffset is subtracted!)"
                )
                return
            }
            executeFrequencyChangeCommand(
                commandToByteArray(
                    RTL_TCP_COMMAND_SET_FREQUENCY,
                    actualSourceFrequency.toInt()
                )
            )
        }
        flushQueue()
        this.frequency = actualSourceFrequency
        iqConverter.frequency = frequency
    }

    fun getMaxFrequency(): Long =
        if (isAllowOutOfBoundFrequency) 3000000000L + frequencyOffset else MAX_FREQUENCY[tuner] + frequencyOffset

    fun getMinFrequency(): Long =
        if (isAllowOutOfBoundFrequency) 0L + frequencyOffset else MIN_FREQUENCY[tuner] + frequencyOffset

    fun getMaxSampleRate(): Int = OPTIMAL_SAMPLE_RATES.last()
    fun getMinSampleRate(): Int = OPTIMAL_SAMPLE_RATES.first()

    fun getNextHigherOptimalSampleRate(sampleRate: Int): Int {
        for (opt in OPTIMAL_SAMPLE_RATES) {
            if (sampleRate < opt) return opt
        }
        return OPTIMAL_SAMPLE_RATES.last()
    }

    fun getNextLowerOptimalSampleRate(sampleRate: Int): Int {
        for (i in 1 until OPTIMAL_SAMPLE_RATES.size) {
            if (sampleRate <= OPTIMAL_SAMPLE_RATES[i]) return OPTIMAL_SAMPLE_RATES[i - 1]
        }
        return OPTIMAL_SAMPLE_RATES.last()
    }

    fun getSupportedSampleRates(): IntArray = OPTIMAL_SAMPLE_RATES

    fun isManualGain(): Boolean = manualGain
    fun setManualGain(enable: Boolean) {
        if (isOpen()) {
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_GAIN_MODE, if (enable) 1 else 0))
        }
        this.manualGain = enable
    }

    fun getGain(): Int = gain
    fun getPossibleGainValues(): IntArray = POSSIBLE_GAIN_VALUES[tuner]
    fun setGain(gain: Int) {
        if (isOpen()) {
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_GAIN, gain))
        }
        this.gain = gain
    }

    fun getIFGain(): Int = ifGain
    fun getPossibleIFGainValues(): IntArray {
        return if (tuner == RTLSDR_TUNER_E4000) {
            IntArray(54) { it + 3 }
        } else {
            intArrayOf(0)
        }
    }

    fun setIFGain(ifGain: Int) {
        if (isOpen() && tuner == RTLSDR_TUNER_E4000) {
            executeCommand(
                commandToByteArray(
                    RTL_TCP_COMMAND_SET_IFGAIN,
                    0.toShort(),
                    ifGain.toShort()
                )
            )
        }
        this.ifGain = ifGain
    }

    fun getFrequencyCorrection(): Int = frequencyCorrection
    fun setFrequencyCorrection(ppm: Int) {
        if (isOpen()) {
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_FREQ_CORR, ppm))
        }
        this.frequencyCorrection = ppm
    }

    fun isAutomaticGainControl(): Boolean = automaticGainControl
    fun setAutomaticGainControl(enable: Boolean) {
        if (isOpen()) {
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_AGC_MODE, if (enable) 1 else 0))
        }
        this.automaticGainControl = enable
    }

    fun getFrequencyOffset(): Int = frequencyOffset
    fun setFrequencyOffset(frequencyShift: Int) {
        this.frequencyOffset = frequencyShift
        iqConverter.frequency = (frequency + frequencyShift)
    }

    fun setDirectSamplingMode(value: Int) {
        if (value !in 0..2) return
        if (isOpen()) {
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_DIRECT_SAMPLING_MODE, value))
        }
        this.directSamplingMode = value
    }

    fun getPacketSize(): Int = PACKET_SIZE
    fun getBytesPerSample(): Int = 2

    fun getPacket(timeout: Int): ByteArray? {
        return try {
            queue.poll(timeout.toLong(), TimeUnit.MILLISECONDS)
        } catch (e: InterruptedException) {
            Log.e(LOGTAG, "getPacket: Interrupted: ${e.message}")
            null
        }
    }

    fun returnPacket(buffer: ByteArray) {
        returnQueue.offer(buffer)
    }

    fun startSampling() {
        if (receiverJob != null) return
        receiverJob = sourceScope?.launch {
            receiverLoop()
        }
    }

    fun stopSampling() {
        receiverJob?.cancel()
        receiverJob = null
    }

    fun fillPacketIntoSamplePacket(packet: ByteArray, samplePacket: SamplePacket): Int =
        iqConverter.fillPacketIntoSamplePacket(packet, samplePacket)

    fun fillPacketIntoInterleavedBuffer(packet: ByteArray, interleavedBuffer: FloatArray): Boolean =
        iqConverter.fillPacketIntoInterleavedBuffer(packet, interleavedBuffer)

    fun mixPacketIntoSamplePacket(
        packet: ByteArray,
        samplePacket: SamplePacket,
        channelFrequency: Long
    ): Int = iqConverter.mixPacketIntoSamplePacket(packet, samplePacket, channelFrequency)

    fun flushQueue() {
        for (i in 0 until QUEUE_SIZE) {
            val buffer = queue.poll() ?: return
            returnPacket(buffer)
        }
    }

    private fun commandToByteArray(command: Int, arg: Int): ByteArray {
        return byteArrayOf(
            command.toByte(),
            ((arg shr 24) and 0xff).toByte(),
            ((arg shr 16) and 0xff).toByte(),
            ((arg shr 8) and 0xff).toByte(),
            (arg and 0xff).toByte()
        )
    }

    private fun commandToByteArray(command: Int, arg1: Short, arg2: Short): ByteArray {
        return byteArrayOf(
            command.toByte(),
            ((arg1.toInt() shr 8) and 0xff).toByte(),
            (arg1.toInt() and 0xff).toByte(),
            ((arg2.toInt() shr 8) and 0xff).toByte(),
            (arg2.toInt() and 0xff).toByte()
        )
    }

    private fun executeCommand(command: ByteArray): Boolean {
        return commandQueue.offer(command)
    }

    private fun executeFrequencyChangeCommand(command: ByteArray) {
        frequencyChangeCommandQueue.poll()
        frequencyChangeCommandQueue.offer(command)
    }

    private suspend fun connect(timeoutMillis: Int): Boolean = withContext(Dispatchers.IO) {
        try {
            val timeoutTime = System.currentTimeMillis() + timeoutMillis
            while (isActive && socket == null && System.currentTimeMillis() < timeoutTime) {
                try {
                    val s = Socket()
                    val sockAddr = InetSocketAddress(ipAddress, port)
                    s.connect(sockAddr, 500)
                    socket = s
                } catch (e: IOException) {
                    delay(100.milliseconds)
                }
            }

            val currentSocket = socket ?: return@withContext false
            currentSocket.tcpNoDelay = true
            currentSocket.soTimeout = 1000

            inputStream = currentSocket.getInputStream()
            outputStream = currentSocket.getOutputStream()
            val buffer = ByteArray(4)

            if (inputStream?.read(buffer) != 4) return@withContext false
            magic = String(buffer, Charsets.US_ASCII)

            if (inputStream?.read(buffer) != 4) return@withContext false
            tuner = buffer[3].toInt()
            if (tuner <= 0 || tuner >= TUNER_STRING.size) return@withContext false

            if (inputStream?.read(buffer) != 4) return@withContext false

            Log.i(
                LOGTAG,
                "Connected to RTL-SDR (Tuner: ${TUNER_STRING[tuner]}; magic: $magic; gain count: ${buffer[3]}) at $ipAddress:$port"
            )
            name = "RTL-SDR (${TUNER_STRING[tuner]}) at $ipAddress:$port"

            if (!isAllowOutOfBoundFrequency) {
                frequency = frequency.coerceIn(MIN_FREQUENCY[tuner], MAX_FREQUENCY[tuner])
            }
            iqConverter.frequency = frequency + frequencyOffset
            sampleRate = sampleRate.coerceIn(getMinSampleRate(), getMaxSampleRate())

            for (gainStep in getPossibleGainValues()) {
                if (gainStep >= gain) {
                    gain = gainStep
                    break
                }
            }

            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_FREQUENCY, frequency.toInt()))
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_SAMPLERATE, sampleRate))
            executeCommand(
                commandToByteArray(
                    RTL_TCP_COMMAND_SET_GAIN_MODE,
                    if (manualGain) 1 else 0
                )
            )
            if (manualGain) executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_GAIN, gain))
            if (manualGain && tuner == RTLSDR_TUNER_E4000) executeCommand(
                commandToByteArray(
                    RTL_TCP_COMMAND_SET_IFGAIN,
                    0.toShort(),
                    ifGain.toShort()
                )
            )
            executeCommand(commandToByteArray(RTL_TCP_COMMAND_SET_FREQ_CORR, frequencyCorrection))
            executeCommand(
                commandToByteArray(
                    RTL_TCP_COMMAND_SET_AGC_MODE,
                    if (automaticGainControl) 1 else 0
                )
            )
            executeCommand(
                commandToByteArray(
                    RTL_TCP_COMMAND_SET_DIRECT_SAMPLING_MODE,
                    directSamplingMode
                )
            )

            true
        } catch (e: Exception) {
            Log.e(LOGTAG, "Connection error: ${e.message}")
            false
        }
    }

    private suspend fun commandLoop() = withContext(Dispatchers.IO) {
        while (isActive) {
            val nextCommand = commandQueue.poll(100, TimeUnit.MILLISECONDS)
                ?: frequencyChangeCommandQueue.poll()
                ?: continue

            try {
                outputStream?.write(nextCommand)
            } catch (e: IOException) {
                reportError("Error while sending command")
                break
            }
        }
    }

    private suspend fun receiverLoop() = withContext(Dispatchers.IO) {
        var buffer: ByteArray? = null
        var index = 0

        try {
            while (isActive) {
                if (buffer == null) {
                    buffer = returnQueue.poll(1000, TimeUnit.MILLISECONDS)
                    index = 0
                }

                val currentBuffer = buffer ?: break
                val bytesRead =
                    inputStream?.read(currentBuffer, index, currentBuffer.size - index) ?: -1

                if (bytesRead <= 0) {
                    reportError("Error while receiving samples.")
                    break
                }

                index += bytesRead
                if (index == currentBuffer.size) {
                    queue.offer(currentBuffer)
                    buffer = null
                }
            }
        } finally {
            buffer?.let { returnQueue.offer(it) }
        }
    }

    /**
     * Callback interface for asynchronous interactions with the source.
     */
    interface Callback {
        /**
         * This method will be called when the source is ready to use after the application
         * called open()
         *
         * @param source    A reference to the IQSource that is now ready
         */
        fun onIQSourceReady(source: RtlsdrSource?)

        /**
         * This method will be called when there is an error with the source
         *
         * @param source    A reference to the IQSource that caused the error
         * @param message    Description of the error
         */
        fun onIQSourceError(
            source: RtlsdrSource?,
            message: String?
        )
    }

    companion object {
        const val RTLSDR_TUNER_UNKNOWN = 0
        const val RTLSDR_TUNER_E4000 = 1
        const val RTLSDR_TUNER_FC0012 = 2
        const val RTLSDR_TUNER_FC0013 = 3
        const val RTLSDR_TUNER_FC2580 = 4
        const val RTLSDR_TUNER_R820T = 5
        const val RTLSDR_TUNER_R828D = 6
        val TUNER_STRING =
            arrayOf("UNKNOWN", "E4000", "FC0012", "FC0013", "FC2580", "R820T", "R828D")

        const val RTL_TCP_COMMAND_SET_FREQUENCY = 0x01
        const val RTL_TCP_COMMAND_SET_SAMPLERATE = 0x02
        const val RTL_TCP_COMMAND_SET_GAIN_MODE = 0x03
        const val RTL_TCP_COMMAND_SET_GAIN = 0x04
        const val RTL_TCP_COMMAND_SET_FREQ_CORR = 0x05
        const val RTL_TCP_COMMAND_SET_IFGAIN = 0x06
        const val RTL_TCP_COMMAND_SET_AGC_MODE = 0x08
        const val RTL_TCP_COMMAND_SET_DIRECT_SAMPLING_MODE = 0x09
        val COMMAND_NAME = arrayOf(
            "invalid",
            "SET_FREQUENY",
            "SET_SAMPLERATE",
            "SET_GAIN_MODE",
            "SET_GAIN",
            "SET_FREQ_CORR",
            "SET_IFGAIN",
            "SET_TEST_MODE",
            "SET_ADC_MODE",
            "SET_DIRECT_SAMPLING_MODE"
        )

        private const val LOGTAG = "RtlsdrSource"
        private const val QUEUE_SIZE = 20
        val OPTIMAL_SAMPLE_RATES = intArrayOf(1000000, 2000000, 2500000)
        val MIN_FREQUENCY =
            longArrayOf(0, 52000000L, 22000000L, 22000000L, 146000000L, 24000000L, 24000000L)
        val MAX_FREQUENCY = longArrayOf(
            0,
            2200000000L,
            948000000L,
            1100000000L,
            924000000L,
            1766000000L,
            1766000000L
        )
        val POSSIBLE_GAIN_VALUES = arrayOf(
            intArrayOf(0), // invalid
            intArrayOf(-10, 15, 40, 65, 90, 115, 140, 165, 190, 215, 240, 290, 340, 420), // E4000
            intArrayOf(-99, -40, 71, 179, 192), // FC0012
            intArrayOf(
                -99,
                -73,
                -65,
                -63,
                -60,
                -58,
                -54,
                58,
                61,
                63,
                65,
                67,
                68,
                70,
                71,
                179,
                181,
                182,
                184,
                186,
                188,
                191,
                197
            ), // FC0013
            intArrayOf(0), // FC2580
            intArrayOf(
                0,
                9,
                14,
                27,
                37,
                77,
                87,
                125,
                144,
                157,
                166,
                197,
                207,
                229,
                254,
                280,
                297,
                328,
                338,
                364,
                372,
                386,
                402,
                421,
                434,
                439,
                445,
                480,
                496
            ), // R820T
            intArrayOf(
                0,
                9,
                14,
                27,
                37,
                77,
                87,
                125,
                144,
                157,
                166,
                197,
                207,
                229,
                254,
                280,
                297,
                328,
                338,
                364,
                372,
                386,
                402,
                421,
                434,
                439,
                445,
                480,
                483,
                496
            ) // R828D
        )
        const val PACKET_SIZE = 16384
    }
}
